<?php
/**
* @file
* Forms Forcontu
*/
/**
* Implements hook_menu().
*/
function forms_forcontu_menu() {
  $items['forms_forcontu/form1'] = array(
  'title' => t('Form 1'),
  'page callback' => 'drupal_get_form',
  'page arguments' => array('forms_forcontu_form1'),
  'access callback' => TRUE,
  'description' => t('Example Form 1'),
  'type' => MENU_CALLBACK,
);
$items['forms_forcontu/form2'] = array(
  'title' => 'Example Form 2',
  'description' => 'Distintos elementos de formulario.',
  'page callback' => 'drupal_get_form',
  'page arguments' => array('forms_forcontu_form2'),
  'access callback' => TRUE,
  'type' => MENU_CALLBACK,
);
$items['forms_forcontu/form3'] = array(
  'title' => t('Form 3'),
  'page callback' => 'drupal_get_form',
  'page arguments' => array('forms_forcontu_form3'),
  'access callback' => TRUE,
  'description' => t('Example Form 3'),
  'type' => MENU_CALLBACK,
);
return $items;
}

/**
* Función retorno para la página forms_forcontu/form1.
*/
function forms_forcontu_form1($form_state) {
$form['description'] = array(
  '#type' => 'item',
  '#title' => t('Formulario 1'),
 );
$form['first_name'] = array(
  '#type' => 'textfield',
  '#title' => t('Nombre'),
);
$form['last_name'] = array(
  '#type' => 'textfield',
  '#title' => t('Apellidos'),
  '#required' => TRUE,
);
$form['submit'] = array(
  '#type' => 'submit',
   '#value' => 'Enviar',
);
return $form;
}

/**
* Función de retorno para la página forms_forcontu/form2.
*/
function forms_forcontu_form2(&$form_state){
// Contenedor para pestañas verticales
$form['tabs'] = array (
'#type' => 'vertical_tabs',
);
// Bloque de información de la cuenta de usuario
$form['tabs']['account_info'] = array(
'#type' => 'fieldset',
'#title' => t('Información de la cuenta'),
'#collapsible' => TRUE,
'#collapsed' => FALSE,
);
$form['tabs']['account_info']['email'] = array(
'#type' => 'textfield',
'#title' => t('E-mail'),
'#default_value' => 'E-mail de usuario',
'#size' => 30,
'#maxlength' => 30,
'#required' => TRUE,
);
$form['tabs']['account_info']['pass'] = array(
'#type' => 'password_confirm',
'#title' => t('Password'),
'#size' => 15,
);
$form['tabs']['account_info']['signature'] = array(
'#type' => 'textfield',
'#title' => 'Tu firma',
'#default_value' => 'Firma',
'#size' => 30,
'#maxlength' => 30,
);
// Bloque de información personal
$form['tabs']['personal_info'] = array(
'#type' => 'fieldset',
'#title' => 'Información personal',
'#collapsible' => TRUE,
'#collapsed' => FALSE,
);
$form['tabs']['personal_info']['first_name'] = array(
'#type' => 'textfield',
'#title' => 'Nombre',
'#required' => TRUE,
'#default_value' => "Nombre",
'#description' => "Escriba su nombre",
'#size' => 20,
'#maxlength' => 20,
);
$form['tabs']['personal_info']['last_name'] = array(
'#type' => 'textfield',
'#title' => 'Apellidos',
'#required' => TRUE,
'#default_value' => "Apellidos",
'#description' => "Escriba sus apellidos",
'#size' => 40,
'#maxlength' => 40,
);
$form['tabs']['personal_info']['ejemplo_imagen_fid'] = array(
'#title' => 'Tu foto',
'#type' => 'managed_file',
'#description' => t('La imagen subida  será mostrada en tu perfil.' ),
'#default_value' => variable_get('image_demo_form', ''),
'#upload_location' => '/sites/default/files',
);
$form['tabs']['personal_info']['months'] = array(
'#type' => 'select',
'#title' => t('Month'),
'#default_value' => 'january',
'#options' => array(
'january' => t('January'),
'february' => t('February'),
'march' => t('March'),
'april' => t('April'),
'may' => t('May'),
'june' => t('June'),
'july' => t('July'),
'august' => t('August'),
'september' => t('September'),
'october' => t('October'),
'november' => t('November'),
'december' => t('December'),
),
'#description' => t('Selecciona mes de nacimiento'),
);
// Bloque de información profesional
$form['tabs']['professional_info'] = array(
'#type' => 'fieldset',
'#title' => 'Información profesional',
'#collapsible' => TRUE,
'#collapsed' => FALSE,
);
$form['tabs']['professional_info']['new_upload'] = array(
'#type' => 'file',
'#title' =>'Adjunta tu CV',
'#size' => 40,
'#attributes' => array('enctype' => "multipart/form-data"),
);
// Envío de formulario
$form['submit'] = array(
'#type' => 'submit',
'#value' => t('Enviar'),
);
return $form;
}
/**
* Función de envío del formulario forms_forcontu_form2
*/
function forms_forcontu_form2_submit($form, &$form_state){
drupal_set_message ("<strong>Su cuenta de usuario ha sido creada 
correctamente.</strong>");
drupal_goto("");
}

function forms_forcontu_form3($form_state) {
$form['personal_data'] = array(
'#type' => 'fieldset',
'#title' => t('Datos Personales'),
'#collapsible' => TRUE,
'#collapsed' => FALSE,
);
$form['personal_data']['first_name'] = array(
'#type' => 'textfield',
'#title' => t('Nombre'),
'#required' => TRUE,
'#default_value' => "Nombre",
'#description' => "Escriba su nombre",
'#size' => 20,
'#maxlength' => 20,
'#weight' => 0,
);
$form['personal_data']['last_name'] = array(
'#type' => 'textfield',
'#title' => t('Apellidos'),
'#required' => TRUE,
'#default_value' => "Apellidos",
'#description' => "Escriba sus apellidos",
'#size' => 40,
'#maxlength' => 40,
'#weight' => 1,
);
$form['personal_data']['email'] = array(
'#type' => 'textfield',
'#title' => t('e-mail'),
'#description' => "Escriba su email",
'#size' => 40,
'#maxlength' => 40,
'#weight' => 2,
);
$form['personal_data']['address'] = array(
'#type' => 'textarea',
'#title' => t('Dirección'),
'#weight' => 3,
);
$form['personal_data']['paises'] = array(
'#type' => 'select',
'#title' => t('Paises'),
'#default_value' => '',
'#options' => array(
'es' => t('España'),
'fr' => t('Francia'),
'ru' => t('Reino Unido'),
'us' => t('USA'),
'it' => t('Italia'),
),
'#description' => t('Selecciona el pais'),
'#weight' => 4,
);

$form['acces_data'] = array(
'#type' => 'fieldset',
'#title' => t('Datos de acceso'),
'#collapsible' => TRUE,
'#collapsed' => FALSE,
);
$form['acces_data']['user'] = array(
'#type' => 'textfield',
'#title' => t('Usuario'),
'#required' => TRUE,
'#description' => "Escriba su nombre de usuario",
'#size' => 20,
'#maxlength' => 20,
);
$form['acces_data']['password'] = array(
'#type' => 'password_confirm',
'#required' => TRUE,
'#description' => "Escriba su contraseña",
'#size' => 20,
'#maxlength' => 20,
);

$options = user_roles();

$form['acces_data']['roles'] = array(
'#type' => 'checkboxes',
'#title' => t('Roles'),
'#options' => $options,
'#description' => t('Select your role.'),
);

// Envío de formulario
$form['submit'] = array(
'#type' => 'submit',
'#value' => t('Enviar'),

);

return $form;
}

/**
* Función de validación del formulario forms_forcontu_form3
*/
function forms_forcontu_form3_validate($form, &$form_state){
//validacion email
if (!valid_email_address($form_state['values']['email'])) {
form_set_error('email', t('You must enter a valid e-mail 
address.'));
}
//Validacion del pais
$vocales= array ("a","e","i","o","u","A","E","I","O","U");
$p_letra=substr($form_state['values']['paises'],0,1);
if (!in_array($p_letra,$vocales)){
  form_set_error('paises', t('You must enter a valid country. Tiene que empezar por vocal'));
}
//Validacion nombre usuario
$x=1;
$y=1;
$z=1;
$numeros= array (1,2,3,4,5,6,7,8,9);
$p_letraus=substr($form_state['values']['user'],0,1);
if (!in_array($p_letraus,$numeros)){
  $x=0;}
$n_char=strlen($form_state['values']['user']);
if ($n_char>=6 && $n_char<=15){
  $y=0;}
if (ctype_alnum ($form_state['values']['user'])){
  $z=0;
}
if ($x!=0 || $y!=0 || $z!=0){
  form_set_error('user', t('El nombre de usuario debe tener entre 6 y 15 caracteres (ambos inclusive). El nombre de usuario sólo puede contener caracteres alfanuméricos (a-z,A-Z,0-9). Además, no podrá empezar por un número.'));
}
//Validacion Contraseña
//$j=1;
//$k=1;
//$p_char=strlen($form_state['values']['password']);
//if ($n_char>=5 && $n_char<=10){
//  $j=0;}
//$patron='(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$';
//$k=drupal_match_path($form_state['values']['password'],$patron);
//if ($j!=0 || $k){
//  form_set_error('password', t('La contraseña tendrá que tener entre 5 y 10 caracteres (ambos inclusive). La contraseña se tiene que componer al menos de una letra en mayúsculas, una letra en minúsculas, un número y un carácter no alfanumérico (por ejemplo un punto o una coma).'));
//}
}

/**
* Función de envío del formulario forms_forcontu_form2
*/
function forms_forcontu_form3_submit($form, &$form_state){
// Función de inserción de datos
global $user; 
$usuario=$user->uid;
$date=time();

$form_state['values'];

$result = db_insert('forms_forcontu')
->fields(array(
'iduser' => $usuario,
'nombre' => $form_state['values']['first_name'],
'apellidos' => $form_state['values']['last_name'],
'email' =>$form_state['values']['email'],
'direccion' => $form_state['values']['address'],
'pais' => $form_state['values']['paises'],
'nombre_user' => $form_state['values']['user'],
'password' => $form_state['values']['password'],
'fecha' => $date,
))
->execute();


drupal_set_message ("<strong>Su cuenta de usuario ha sido creada correctamente.</strong>");
if ($form_state['values']['paises']=="es"){
    drupal_goto("destino/spain");
}
if ($form_state['values']['paises']!="es"){
    drupal_goto("destino/otros");
}
}